<h1>Login</h1>

<?php if (isset($error)): ?>
  <div class="alert alert-danger">
    <?= $this->escapeHtml($error); ?>
  </div>
<?php endif; ?>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <?= $this->form()->openTag($form); ?>

      <div class="form-group">
        <?= $this->formLabel($form->get('username')); ?>
        <?= $this->formElement($form->get('username')); ?>
        <?= $this->formElementErrors($form->get('username')); ?>
      </div>

      <div class="form-group">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElementErrors($form->get('password')); ?>
      </div>

      <!-- Optional: Tambahkan elemen CSRF jika ada -->
      <?= $this->formElement($form->get('csrf')); ?>

      <div class="form-group mt-2">
        <?= $this->formSubmit($form->get('submit')); ?>
        <a href="<?= $this->url('register'); ?>" class="btn btn-secondary ">Register</a>
      </div>

      <!-- Tambahkan tombol untuk redirect ke halaman registrasi -->
      <div class="form-group">
      </div>

      <?= $this->form()->closeTag(); ?>
    </div>
  </div>
</div>