<h1>Contact Us</h1>

<?php if (isset($this->message)): ?>
    <div class="alert alert-success">
        <?= $this->message; ?>
    </div>
<?php endif; ?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('name')); ?>
    <?= $this->formElement($form->get('name')); ?>
    <?= $this->formElementErrors($form->get('name')); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('email')); ?>
    <?= $this->formElement($form->get('email')); ?>
    <?= $this->formElementErrors($form->get('email')); ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('message')); ?>
    <?= $this->formElement($form->get('message')); ?>
    <?= $this->formElementErrors($form->get('message')); ?>
</div>

<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
